/** Pedido explícito de jogo compartilhado, não toda menção casual a brincar. */
export function pedidoExplicitoDeBrincadeira(texto: string): boolean {
  const t = texto.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  return /\b(?:quero|queria|gostaria|preciso|me (?:de|da|mostre|sugira|ensine)|pode (?:me )?(?:dar|sugerir|ensinar|passar)|sugira|indique|invente|crie|monte|tem (?:alguma|uma))\b.{0,110}\b(?:brincadeiras?|brincar|jogos?|atividade ludica)\b/.test(t);
}

/** Critério de experiência, não nova fonte clínica nem substituto das BPs. */
export const BLOCO_PEDIDO_BRINCADEIRA = `<pedido_explicito_de_brincadeira>
A família pediu brincadeira AGORA. Ofereça TRÊS opções de jogo para a família poder experimentar uma hoje e guardar as outras para depois. Cada opção precisa ser uma experiência compartilhada divertida mesmo sem o objetivo de desenvolvimento. Não reembale um treino, uma simulação da situação difícil ou uma atividade já tentada como se fosse jogo novo. Use um interesse forte da criança para tornar UMA opção especial; não repita o mesmo personagem, enredo ou objeto nas três. As outras podem aproveitar outra preferência, uma ação do lugar ou o humor da relação entre adulto e criança. Personalizar não é só repetir o tema favorito.

As três opções devem ter MECÂNICAS diferentes entre si e diferentes das já tentadas. Compare as ações, não só os nomes: restaurante seguido de receita/cozinha ainda é a mesma mecânica de escolher e servir comida; expedição, caça e carrinho em missão podem ser a mesma busca reembalada. No máximo UMA pode ser achar/esconder algo; no máximo UMA pode ser criar uma regra ou escolher o trajeto. Outras formas possíveis: faz-de-conta com personagem, adivinhação por pistas, imitação engraçada com troca de papéis, transformar uma compra em personagem com pequena aventura — só se couberem no lugar e no Perfil. Em cada opção, dê o mínimo para executar sem improvisar o resto: material ou cenário, como começar, uma FALA EXATA de abertura do adulto, uma resposta possível da criança no modo em que ela de fato se comunica, o que o adulto faz em seguida e um momento de descoberta, surpresa ou humor. O leitor deve conseguir brincar sem inventar as falas nem adivinhar o próximo turno. Se a criança usa gestos, mostre o gesto ou escolha plausível e a reação imediata do adulto; não escreva uma fala hipotética da criança como condição para continuar. Variem também o PAPEL do adulto: errar de propósito pode tornar UM jogo divertido, mas não deve ser o truque repetido nas três opções. Em outra, a criança pode virar quem dá a pista, esconde algo ou cria a regra. Só andar, encontrar e apontar três vezes não é suficiente. Ela pode apontar, mover, gesticular ou falar conforme sua comunicação; não exija fala nem olhar. Use idade, interesses e sensibilidades para mudar as ações do jogo, não só o título. Uma frase comum ao fim pode dizer como facilitar ou encerrar sem cobrança.

Em TODAS as três opções, acrescente uma frase curta de valor, naturalmente: "Aqui ela pratica ..." ou "Isso convida a ...". Nomeie apenas UMA capacidade que aquela ação realmente convida a usar — por exemplo atenção compartilhada, alternância, escolha, comunicação ou flexibilidade — e diferencie as três quando couber. Confira antes de responder: nenhum dos três blocos pode ficar sem essa ligação concreta, e a habilidade nomeada deve corresponder à ação descrita (criar uma regra não é, por si só, praticar flexibilidade). A alegria e a conexão também são valor, não só treino. Calibre a complexidade pela idade e pelo que o Perfil diz que esta criança faz hoje; idade não é prova de que ela "já deveria" executar uma habilidade. Se ela se comunica por gestos, apontar e escolher já são comunicação. Convide uma palavra curta apenas se o Perfil indicar fala emergente, sem exigir que a criança repita para ganhar a vez. Não prometa que a brincadeira vai melhorar uma habilidade nem faça explicação de neurodesenvolvimento.

Quando Perfil ou conversa indicam sensibilidade a sons, texturas ou cheiros, NÃO reproduza nem simule esse estímulo na brincadeira — nem em intensidade baixa — a menos que a família peça expressamente um ensaio sensorial. Evite sustos inesperados. O jogo acontece em ambiente confortável. Se um lugar é o contexto do pedido (mercado, parque, escola) e a família não pediu preparação em casa, trate como brincadeiras DURANTE a ida: as três opções devem poder acontecer ali, de modo discreto e sem material trabalhoso. Use coisas que realmente há no lugar; não presuma que haverá figuras do interesse da criança em prateleiras ou paredes. No mercado, itens da compra e corredores podem virar pistas, escolhas ou personagens imaginários, com alternância de papéis — não um quiz de nomeação. Use um marco previsível, como o próximo corredor, não cada novo som. Se a criança já está sobrecarregada, a saída ou pausa vem antes de qualquer jogo. Primeiro faça a brincadeira existir por si; só depois, se útil, ligue-a à situação real em uma frase. Manejo da situação real não ocupa o lugar da brincadeira.

Se um gesto de pausa puder ser útil, ele pertence à escolha espontânea da criança durante o jogo. Não interrompa a brincadeira periodicamente para o adulto fazer o gesto e a criança copiá-lo: isso voltaria a ser exercício disfarçado. NENHUMA das três opções pode ser apenas pedir pausa, buscar corredor mais calmo, escolher trajeto, respirar ou ensaiar lidar com barulho. Essas são estratégias de manejo, não brincadeiras. A pausa e a saída aparecem somente no aviso final, fora das três opções. Em cada jogo deve haver pelo menos uma virada lúdica que faça a criança querer repetir a vez — surpresa, faz-de-conta ou humor, sem susto e sem estímulo sensorial desconfortável. O gesto ou a escolha da criança precisa CAUSAR a virada; não acrescente uma descoberta aleatória após ela apontar. Mostre como a segunda rodada muda ou como os papéis se invertem, para a mãe não ficar sem saber como continuar. Se tirar a meta de desenvolvimento e o jogo deixar de ter graça, substitua a opção antes de responder.

SAÍDA: comece diretamente por três blocos com • ou emoji + título curto em negrito, separados por UMA linha em branco. São alternativas, não etapas; não as numere como sequência. Não coloque a primeira opção no parágrafo introdutório. Em cada bloco, use linhas curtas SEM linhas vazias internas: cenário/começo; "Você: ..." com frase pronta; "Ela: ..." com gesto/ação ou palavra possível; "Então: ..." com sua reação e a virada divertida; e uma linha curta com UMA capacidade convidada. Pode juntar linhas se ficar natural, mas NÃO omita os turnos concretos para caber em um limite artificial de palavras. Não transforme o jogo em ficha técnica ou diálogo longo. Se o histórico diz que já fizeram restaurante, descarte chef/cozinha/receita/servir como mecânica, mesmo que a criança goste de comida; use o interesse dela de outro modo. Não recorra automaticamente a cozinhar/servir quando o cenário é mercado: isso pode repetir a mesma mecânica, sem aproveitar o lugar. Depois das três opções, no máximo uma frase para sugerir por qual começar e outra para lembrar que pausa ou saída vem primeiro se ela estiver desconfortável. Não repita a recomendação antes e depois da lista. O objetivo técnico fica por trás. Não ofereça tutorial de história ou link do Lúdico neste pedido.
</pedido_explicito_de_brincadeira>`;
