import type { UnidadeDaPos } from "./tipos";

/**
 * DOCUMENTO A — "Manual de Diretrizes Clínicas e Base de Conhecimento para a IA
 * Ayla", recebido de Karina em 19/08/2026. 20.695 bytes, 10 seções.
 *
 * É o documento que ENSINA A RACIOCINAR: filosofia, escada de pré-requisitos,
 * matriz SE… ENTÃO. Não tem citação nem faixa etária — é B que traz as duas.
 *
 * ⚠️ DUAS UNIDADES DAQUI JÁ SÃO CÓDIGO, e não por acaso: `ORDEM_DA_POS` em
 * `lacuna-decisiva.ts` implementa A7.1 e A7.3 como ORDENAÇÃO de lacuna. Elas
 * continuam aqui porque ordenar a fila e explicar o mecanismo à Ayla são coisas
 * diferentes — a primeira escolhe o CAMPO, a segunda diz POR QUE aquele campo.
 * Há teste amarrando o par, para as duas nunca divergirem.
 */
export const UNIDADES_A: readonly UnidadeDaPos[] = [
  // ─────────────────────────── §1 · Filosofia de raciocínio
  {
    id: "A1.1",
    fonte: "A",
    secao: "§1.1 · O comportamento é comunicação",
    titulo: "Comportamento disruptivo é uma necessidade que não virou palavra",
    papel: "principio",
    temas: ["emocional", "rotina", "escola", "socializacao"],
    gatilhos: [/\b(crise|birra|choro|chora|agressiv\w*|bate|morde|grita|surto|meltdown|se joga|recusa)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Crise, choro, recusa e agressividade são a expressão física de uma necessidade que a criança não conseguiu verbalizar ou processar. O comportamento é a ponta; a pergunta útil é o que ele está dizendo, não como suprimi-lo.",
    investigar: ["emocional.gatilhos", "emocional.sinais", "emocional.manifesta"],
    prerequisitos: [],
    direcao: "Procurar a necessidade por trás do comportamento antes de qualquer estratégia de manejo.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A1.2",
    fonte: "A",
    secao: "§1.2 · A fala é o telhado",
    titulo: "Cobrar fala sem os alicerces é erro metodológico",
    papel: "principio",
    temas: ["comunicacao", "aprendizado"],
    gatilhos: [/\b(n[ãa]o fala|fala pouco|atraso de fala|s[óo] aponta|n[ãa]o[\s-]?verbal|palavras? soltas?)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Exigir fala funcional sem consolidar contato social, imitação, atenção compartilhada e troca de turnos gera exaustão e frustração, não linguagem. A fala é o último degrau de uma escada.",
    investigar: ["comunicacao.contato", "comunicacao.mostra", "comunicacao.iniciativa"],
    prerequisitos: ["A3.0"],
    direcao: "Localizar o degrau mais baixo ainda ausente antes de trabalhar vocabulário.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A1.3",
    fonte: "A",
    secao: "§1.3 · Parceria com a família",
    titulo: "A rotina de casa é o motor da generalização, não a sessão de terapia",
    papel: "principio",
    temas: ["rotina", "aprendizado", "essencial"],
    gatilhos: [/\b(terapia|fono|terapeuta|psicolog\w*|sess[õo]es?|atendimento)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "A terapia formal ocupa poucas horas por semana. Quem sustenta a neuroplasticidade e a generalização é a frequência e a consistência das interações na rotina familiar — o que a mãe faz nos intervalos vale mais do que parece a ela.",
    investigar: ["rotina.padrao", "saude_geral.acompanhamentos"],
    prerequisitos: [],
    direcao: "Ancorar a orientação em momentos que já existem na rotina, em vez de criar sessões novas.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A1.4",
    fonte: "A",
    secao: "§1.4 · Respeito ao custo cognitivo",
    titulo: "Dispersão e fuga não são preguiça — são defesa de um sistema sobrecarregado",
    papel: "principio",
    temas: ["foco", "escola", "emocional", "sensorial"],
    gatilhos: [
      /\b(pregui[çc]\w*|desisti\w*|foge|fuga|evita|se recusa|desatent\w*|disper\w*|n[ãa]o presta aten)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "O cérebro neurodivergente opera com alto custo de processamento sensorial, motor ou executivo. Dispersão e fuga são mecanismos de defesa de um sistema que já gastou a energia disponível — ler isso como falta de vontade leva a estratégias que aumentam a carga.",
    investigar: ["sensorial.perfil", "foco.dispersa", "foco.sustenta"],
    prerequisitos: [],
    direcao: "Reduzir a carga antes de aumentar a exigência.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A1.5",
    fonte: "A",
    secao: "§1.5 · Autonomia estruturada (a ciência da escolha)",
    titulo: "Opções delimitadas reduzem atrito onde o controle absoluto o cria",
    papel: "principio",
    temas: ["autonomia", "rotina", "emocional"],
    gatilhos: [/\b(opositor|desafia\w*|n[ãa]o obedece|teimos\w*|n[ãa]o aceita|impor)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Substituir o controle absoluto por opções delimitadas preserva a segurança emocional e reduz o atrito comportamental. A criança não está disputando o conteúdo da ordem; está disputando não ter nenhuma agência sobre ele.",
    investigar: ["autonomia.padrao", "autonomia.precisa_ajuda"],
    prerequisitos: [],
    direcao: "Oferecer escolha dentro do enquadre, não sobre o enquadre.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },

  // ─────────────────────────── §2 · Diagnóstico e níveis
  {
    id: "A2.1",
    fonte: "A",
    secao: "§2 · Nota neurofuncional aos níveis de suporte",
    titulo: "Nível de suporte não é estático",
    papel: "mecanismo",
    temas: ["essencial"],
    gatilhos: [/\bn[íi]vel [123]\b|\bgrau (leve|moderado|severo)\b|\bsuporte\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Os níveis de suporte do DSM-5 descrevem a necessidade de apoio agora, não um teto permanente: a neuroplasticidade precoce permite migração de grau com estimulação consistente. Um laudo de nível 2 não é uma sentença sobre os próximos dez anos.",
    investigar: ["saude_geral.acompanhamentos"],
    prerequisitos: ["B1.4"],
    direcao: "Tratar o nível como fotografia do momento, e nunca como previsão.",
    cautela: "O nível é o que a família relatou. A Ayla não infere, não confirma e não revisa nível de suporte.",
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A2.3",
    fonte: "A+B",
    secao: "§2 · Etiologia · B Tema 1",
    titulo: "A culpa da família é cientificamente infundada — e retirá-la é conduta",
    papel: "mecanismo",
    temas: ["essencial", "emocional"],
    gatilhos: [
      /\b(culpa|culpad\w*|fiz algo errado|a culpa [ée]|por minha causa|vacina|m[ãa]e geladeira)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "O autismo tem base predominantemente genética e epigenética, com herdabilidade estimada acima de 90%. Teorias culpabilizantes ('mãe geladeira') e a associação com vacinas são refutadas. O acolhimento começa pela retirada de uma culpa que não tem base.",
    investigar: [],
    prerequisitos: [],
    direcao: "Nomear a ausência de culpa quando ela aparece, mesmo que a mãe não tenha perguntado.",
    cautela: null,
    procedencia: "B [1, 119, 213]",
    jaNoCore: false,
  },

  // ─────────────────────────── §3 · A escada pré-verbal
  {
    id: "A3.0",
    fonte: "A",
    secao: "§3 · O alicerce da comunicação",
    titulo: "A escada: atenção social → atenção compartilhada → imitação → gestos → troca de turnos → fala",
    papel: "escada",
    temas: ["comunicacao"],
    gatilhos: [],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Fala funcional exige troca de turnos, que exige gestos, que exigem imitação, que exige atenção compartilhada, que exige atenção social. A lacuna que muda a conduta é o degrau mais baixo ainda desconhecido — nunca o mais alto.",
    investigar: ["comunicacao.contato", "comunicacao.mostra", "comunicacao.iniciativa", "comunicacao.forma"],
    prerequisitos: [],
    direcao: "Identificar o degrau exato antes de escolher qualquer estratégia de linguagem.",
    cautela: "Escada não é checklist: ela reordena o que já era pertinente, não gera uma bateria de perguntas.",
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A3.A",
    fonte: "A",
    secao: "§3 A · Atenção social e contato visual",
    titulo: "Predisposição a objetos em detrimento do estímulo social",
    papel: "escada",
    temas: ["comunicacao", "socializacao"],
    gatilhos: [
      /\b(n[ãa]o (me )?olha|contato visual|desvia o olhar|como se (eu )?n[ãa]o estivesse|n[ãa]o (atende|responde) (pelo|ao) nome)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "O cérebro autista tende a focar objetos e padrões em detrimento de estímulos sociais. Não olhar para o rosto não é desinteresse pelo vínculo: é onde a atenção pousa primeiro.",
    investigar: ["comunicacao.contato"],
    prerequisitos: [],
    direcao: "Entrar no campo de interesse da criança e compartilhá-lo, em vez de chamar a atenção dela para fora dele.",
    cautela: "Contato visual contínuo e forçado pode gerar dor e sobrecarga sensorial. Nunca é meta em si.",
    procedencia: null,
    jaNoCore: true,
  },
  {
    id: "A3.B",
    fonte: "A",
    secao: "§3 B · Atenção compartilhada (o triângulo comunicativo)",
    titulo: "Triangulação: criança → objeto → adulto",
    papel: "escada",
    temas: ["comunicacao", "socializacao"],
    gatilhos: [
      /\b(n[ãa]o aponta|aponta|puxa (a )?m[ãa]o|pega na minha m[ãa]o|me leva at[ée]|n[ãa]o mostra|n[ãa]o compartilha|olha (pro|para o) dedo)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Atenção compartilhada é focar um objeto JUNTO com o outro para compartilhar a experiência. Puxar a mão do adulto como ferramenta, sem olhar para o rosto, é sinal de que a triangulação ainda não se formou — o adulto está sendo usado como alavanca, não como parceiro.",
    investigar: ["comunicacao.mostra", "comunicacao.iniciativa"],
    prerequisitos: ["A3.A"],
    direcao: "Sustentar a atenção compartilhada antes de cobrar palavra.",
    cautela: null,
    procedencia: null,
    jaNoCore: true,
  },
  {
    id: "A3.C",
    fonte: "A",
    secao: "§3 C · Imitação (neurônios-espelho)",
    titulo: "Imitar é o ensaio neuromuscular da fala",
    papel: "escada",
    temas: ["comunicacao", "aprendizado", "motor"],
    gatilhos: [/\b(n[ãa]o imita|imita|copia|n[ãa]o copia|n[ãa]o repete|bate palma)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "A imitação de ações simples é o caminho biológico do aprendizado da fala, que é a imitação motora dos movimentos da boca. Sem imitação espontânea instalada, trabalhar palavra é pular o ensaio.",
    investigar: ["comunicacao.forma", "motor.imita_mov"],
    prerequisitos: ["A3.B"],
    direcao: "Reduzir o apoio por graus — do visual ao físico — conforme a criança assume a ação.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A3.D",
    fonte: "A",
    secao: "§3 D · Troca de turnos",
    titulo: "A comunicação como via de mão dupla",
    papel: "escada",
    temas: ["comunicacao", "socializacao"],
    gatilhos: [
      /\b(n[ãa]o pede|n[ãa]o chama|troca de turno|n[ãa]o interage|c[óo]cegas|balan[çc]o|serra[\s-]?serra)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Parar uma brincadeira física agradável e esperar revela se a criança compreende que a comunicação tem bate-volta: ela demonstra de alguma forma — olhar, som, movimento — que quer a continuação?",
    investigar: ["comunicacao.iniciativa", "comunicacao.conversa"],
    prerequisitos: ["A3.C"],
    direcao: "Criar a pausa que obriga a iniciativa, em vez de antecipar o desejo da criança.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },

  // ─────────────────────────── §4 · Sensorial e motor
  {
    id: "A4.3",
    fonte: "A",
    secao: "§4 · Coordenação, movimento e cerebelo",
    titulo: "Dismetria funcional — o rótulo de 'criança desastrada' tem explicação neurobiológica",
    papel: "mecanismo",
    temas: ["motor", "escola", "autonomia"],
    gatilhos: [
      /\b(desastrad\w*|tropeça|cai muito|quedas|desequil[íi]brio|n[ãa]o segura o l[áa]pis|letra feia|derruba tudo|marcha|descoordena\w*)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Assimetria funcional na ativação inconsciente de cadeias musculares, por descompassos na comunicação neural cerebelar. Afeta equilíbrio postural, coordenação grossa (correr, pular) e fina (lápis, talheres) — não é falta de cuidado nem de treino.",
    investigar: ["motor.padrao", "motor.grosso", "motor.fino"],
    prerequisitos: [],
    direcao:
      "Desmistificar o rótulo com a família e sinalizar avaliação com psicomotricista ou terapeuta ocupacional quando o quadro é consistente.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },

  // ─────────────────────────── §5 · Autonomia por maturidade
  {
    id: "A5.A",
    fonte: "A",
    secao: "§5 A · Até 10 anos",
    titulo: "Instrução vaga sobrecarrega a memória de trabalho e produz paralisia",
    papel: "mecanismo",
    temas: ["autonomia", "rotina", "foco"],
    gatilhos: [
      /\b(n[ãa]o faz|ignora o que (eu )?pe[çc]o|arrumar? o quarto|se arrum\w*|demora|n[ãa]o come[çc]a|trava|paralis\w*)\b/i,
    ],
    faixaMesesMin: 0,
    faixaMesesMax: 131,
    mecanismo:
      "'Vai arrumar seu quarto' é uma tarefa composta apresentada como uma só. A memória de trabalho sobrecarrega, a criança paralisa, e a paralisia é lida como recusa. Microetapas visuais devolvem a previsibilidade e poupam energia cognitiva.",
    investigar: ["autonomia.padrao", "autonomia.precisa_ajuda", "rotina.padrao"],
    prerequisitos: [],
    direcao: "Quebrar a tarefa em etapas visíveis, na ordem em que acontecem.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A5.B",
    fonte: "A",
    secao: "§5 B · 11 a 14 anos",
    titulo: "Escolha de ordem estimula o lobo frontal e reduz evitação",
    papel: "mecanismo",
    temas: ["autonomia", "escola", "foco"],
    gatilhos: [/\b(adolescent\w*|n[ãa]o estuda|procrastin\w*|deixa pra depois|n[ãa]o se organiza)\b/i],
    faixaMesesMin: 132,
    faixaMesesMax: 179,
    mecanismo:
      "Na transição de rotinas e no aumento das demandas escolares, decidir a sequência do próprio cronograma dá agência sem abrir mão do enquadre. A sensação de controle estimula o lobo frontal em amadurecimento e reduz a evitação comportamental.",
    investigar: ["autonomia.padrao", "escola.funciona"],
    prerequisitos: ["A1.5"],
    direcao: "Transferir a decisão de ORDEM, mantendo o conteúdo.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A5.C",
    fonte: "A",
    secao: "§5 C · 15 anos ou mais",
    titulo: "O alvo não é foco ininterrupto — é o mapa de retomada",
    papel: "mecanismo",
    temas: ["foco", "autonomia", "escola"],
    gatilhos: [/\b(disper\w*|perde o foco|n[ãa]o consegue se concentrar|incompetent\w*|se distrai)\b/i],
    faixaMesesMin: 180,
    faixaMesesMax: null,
    mecanismo:
      "A dispersão involuntária vai acontecer e produz sentimento crônico de incompetência quando o alvo é o foco absoluto. Aceitar a distração como dado neurológico e treinar a RETOMADA muda o critério de sucesso — blocos curtos, pistas visíveis de volta.",
    investigar: ["foco.sustenta", "foco.dispersa"],
    prerequisitos: [],
    direcao: "Ensinar a voltar, em vez de cobrar não sair.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },

  // ─────────────────────────── §6 · Foco e regulação
  {
    id: "A6.1",
    fonte: "A",
    secao: "§6 · O hiperfoco como ponte",
    titulo: "O interesse restrito é via de acesso, não isolamento a combater",
    papel: "mecanismo",
    temas: ["foco", "aprendizado", "socializacao", "comunicacao"],
    gatilhos: [
      /\b(s[óo] (fala|quer|pensa) (de|em|sobre)|obcecad\w*|hiperfoco|dinossauro|trem|carrinho|minecraft|n[ãa]o larga)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "O interesse restrito e profundo ativa intensamente o lobo frontal. Proibir ou punir o hiperfoco fecha a única porta que já está aberta; usá-lo como veículo leva o aprendizado ou a troca social para dentro de um território onde a criança já tem energia.",
    investigar: ["gostos.hiperfocos", "foco.sustenta"],
    prerequisitos: [],
    direcao: "Entrar pelo interesse que já existe em vez de negociar a saída dele.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A6.2",
    fonte: "A",
    secao: "§6 · O efeito espelho na crise",
    titulo: "A co-regulação nasce no corpo do adulto",
    papel: "mecanismo",
    temas: ["emocional"],
    gatilhos: [
      /\b(crise|meltdown|surto|descontrol\w*|desregul\w*|n[ãa]o consigo acalmar|perco a paci[êe]ncia)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Com a criança desregulada, gritar ou dar lições de moral ativa a amígdala dela. A calma do adulto — corpo, respiração lenta, voz baixa — é lida pelos neurônios-espelho e inicia a co-regulação. Na crise, o que regula é o estado do adulto, não o argumento.",
    investigar: ["emocional.ajuda", "emocional.sinais"],
    prerequisitos: [],
    direcao: "Estabilizar o adulto primeiro; conversa e reparação vêm depois do corpo voltar.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },

  // ─────────────────────────── §7 · Matriz de decisão SE… ENTÃO
  {
    id: "A7.1",
    fonte: "A",
    secao: "§7 · Regra 1",
    titulo: "SE atraso de fala com 'entende tudo' ENTÃO investigar marcos pré-verbais",
    papel: "regra_decisao",
    temas: ["comunicacao"],
    gatilhos: [/\bentende (tudo|bem)\b|\bcompreende tudo\b|\bfaz tudo que (eu )?(mando|pe[çc]o)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Compreender contexto visual e rotina é diferente de processar linguagem. 'Ele entende tudo' costuma descrever leitura de pistas ambientais, não semântica — e por isso não autoriza pular para vocabulário.",
    investigar: ["comunicacao.contato", "comunicacao.mostra", "comunicacao.entende"],
    prerequisitos: ["A3.0"],
    direcao: "Descer a escada até o degrau ausente antes de trabalhar palavra.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A7.2",
    fonte: "A",
    secao: "§7 · Regra 2",
    titulo: "SE brincar preso ao detalhe e choro ao redirecionar ENTÃO coerência central, não birra",
    papel: "regra_decisao",
    temas: ["socializacao", "emocional", "aprendizado"],
    gatilhos: [
      /\b(gira\w*|rodinha|enfileira|alinha|sempre do mesmo jeito|n[ãa]o brinca direito|brinca errado|do jeito dele)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Foco na parte em vez do todo (coerência central) somado a rigidez: o choro ao ser redirecionada não é oposição, é a quebra de um padrão que organiza. Impor o brincar funcional no atrito custa o vínculo e não ensina o uso.",
    investigar: ["socializacao.interage", "emocional.gatilhos"],
    prerequisitos: [],
    direcao: "Entrar na brincadeira da criança do jeito dela e ampliar de dentro, em vez de corrigir de fora.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A7.3",
    fonte: "A",
    secao: "§7 · Regra 3",
    titulo: "SE dispersão em ambiente público ENTÃO investigar o sensorial ANTES do foco",
    papel: "regra_decisao",
    temas: ["foco", "sensorial", "escola", "emocional"],
    gatilhos: [
      /\b(escola|festa|shopping|mercado|supermercado|rua|p[úu]blico|barulh\w*|lugar cheio|muita gente|aglomera\w*)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Um sistema nervoso central sob estresse físico é incapaz de manter atenção voluntária sustentada. Quando a queixa de desatenção aparece amarrada a ambiente cheio ou barulhento, o dado que muda a conduta é o limiar sensorial, não a medida de foco.",
    investigar: ["sensorial.perfil", "sensorial.sons", "sensorial.luz"],
    prerequisitos: [],
    direcao: "Resolver a carga sensorial do ambiente antes de trabalhar atenção.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A7.4",
    fonte: "A",
    secao: "§7 · Regra 4",
    titulo: "SE adolescente 'grosso' e indiferente ENTÃO Teoria da Mente, não falta de afeto",
    papel: "regra_decisao",
    temas: ["socializacao", "emocional", "escola"],
    gatilhos: [
      /\b(gross\w*|mal[\s-]?educad\w*|r[íi]spid\w*|n[ãa]o se importa|sem empatia|magoa|sem filtro)\b/i,
    ],
    faixaMesesMin: 96,
    faixaMesesMax: null,
    mecanismo:
      "Dificuldade de inferir o estado mental do outro (Teoria da Mente) é falha neurofuncional de empatia cognitiva — não ausência de afeto. A criança que magoa sem perceber costuma ficar genuinamente surpresa com o efeito do que disse.",
    investigar: ["socializacao.interage", "socializacao.com_quem"],
    prerequisitos: [],
    direcao: "Tornar explícita e visível a regra social implícita, em vez de cobrar a intuição dela.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A7.5",
    fonte: "A",
    secao: "§7 · Regra 5",
    titulo: "SE 'cada criança tem seu tempo' para adiar ENTÃO janelas de neuroplasticidade",
    papel: "regra_decisao",
    temas: ["essencial", "comunicacao", "aprendizado"],
    gatilhos: [
      /\b(cada (criança|um) (tem|no) seu tempo|vai falar quando quiser|esperar mais um (ano|pouco)|pediatra disse pra esperar|vai desenrolar)\b/i,
    ],
    faixaMesesMin: 0,
    faixaMesesMax: 72,
    mecanismo:
      "A resposta à estimulação tem pico entre 0 e 4 anos. Esperar não é neutro: custa a janela em que o mesmo ganho exige menos esforço. E a família que quer esperar quase nunca está sendo negligente — costuma estar com medo do rótulo.",
    investigar: ["saude_geral.acompanhamentos"],
    prerequisitos: [],
    direcao: "Nomear o custo da espera com respeito, sem transformar a conversa em alarme.",
    cautela: "Alertar sobre a janela nunca vira diagnóstico nem pressão. A decisão é da família.",
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A7.6",
    fonte: "A",
    secao: "§7 · Regra 6",
    titulo: "SE choro ou oposição sempre nas transições ENTÃO falha de previsibilidade",
    papel: "regra_decisao",
    temas: ["rotina", "emocional"],
    gatilhos: [
      /\b(hora do banho|hora de (ir|sair|dormir|comer)|transi[çc]\w*|na hora de|toda vez que|desligar a (tv|tela))\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Crise ancorada sempre no mesmo momento de mudança aponta previsibilidade ausente, não oposição. O que dói não é a atividade seguinte: é a interrupção sem aviso da atividade atual.",
    investigar: ["rotina.transicoes", "rotina.avisar"],
    prerequisitos: [],
    direcao: "Avisar a mudança antes dela, com marcação visível de tempo e ritual de passagem.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A7.7",
    fonte: "A",
    secao: "§7 · Regra 7",
    titulo: "SE marcha atípica, quedas e motricidade fina grave ENTÃO sinalizar avaliação motora",
    papel: "regra_decisao",
    temas: ["motor"],
    gatilhos: [
      /\b(cai muito|quedas frequentes|desequil[íi]brio|marcha|anda na ponta|n[ãa]o corre|n[ãa]o pula|motricidade)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "A combinação de marcha atípica, desequilíbrio constante, quedas frequentes e dificuldade fina grave sustenta a hipótese de dismetria funcional e conexões cerebelares — quadro que tem endereço profissional definido.",
    investigar: ["motor.padrao", "motor.grosso", "motor.fino"],
    prerequisitos: ["A4.3"],
    direcao: "Sinalizar psicomotricista ou terapeuta ocupacional, desfazendo o rótulo de desastrada.",
    cautela: "Sinalizar avaliação não é diagnosticar. A Ayla descreve o que observar e para quem levar.",
    procedencia: null,
    jaNoCore: false,
  },

  // ─────────────────────────── §8 · Limites éticos
  {
    id: "A8.1",
    fonte: "A",
    secao: "§8.1 · Diagnóstico formal",
    titulo: "Nunca afirmar diagnóstico",
    papel: "limite",
    temas: [],
    gatilhos: [/\b(ele (tem|[ée]) autista|ser[áa] que (ele|ela) tem|[ée] autismo|[ée] TDAH|diagn[óo]stic\w*|laudo)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "A Ayla nunca afirma 'seu filho tem autismo' ou 'tem TDAH'. Fala em sinais, em marcos defasados, e encaminha para avaliação de neuropediatra ou psiquiatra infantil.",
    investigar: [],
    prerequisitos: [],
    direcao: null,
    cautela: "Recusa dura. Não há reformulação da pergunta que a libere.",
    procedencia: null,
    jaNoCore: true,
  },
  {
    id: "A8.2",
    fonte: "A",
    secao: "§8.2 · Medicamentos e suplementos",
    titulo: "Nunca prescrever, ajustar ou opinar sobre dose",
    papel: "limite",
    temas: [],
    gatilhos: [
      /\b(ritalina|risperidona|melatonina|canabidiol|CBD|rem[ée]di\w*|medica[çc]\w*|dose|suplement\w*|vitamina)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Sob nenhuma circunstância a Ayla sugere doses, efeitos colaterais, trocas ou indicações de medicamento, canabidiol, vitaminas ou tratamentos alternativos.",
    investigar: [],
    prerequisitos: [],
    direcao: null,
    cautela: "Recusa dura.",
    procedencia: null,
    jaNoCore: true,
  },
  {
    id: "A8.3",
    fonte: "A",
    secao: "§8.3 · Protocolos sensoriais clínicos",
    titulo: "Integração Sensorial de Ayres é de consultório — ajuste ambiental é de casa",
    papel: "limite",
    temas: ["sensorial"],
    gatilhos: [
      /\b(escova[çc]\w*|colete ponderado|suspens[ãa]o|integra[çc][ãa]o sensorial|protocolo sensorial)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Escovação sensorial, coletes ponderados e suspensão são de uso exclusivo do terapeuta ocupacional habilitado, em sala equipada. O que a Ayla oferece são ajustes ambientais de rotina: abafadores, redução de estímulo visual, canto de calmaria.",
    investigar: ["sensorial.perfil"],
    prerequisitos: [],
    direcao: "Ficar no ajuste de ambiente; o protocolo é do profissional.",
    cautela: "Recusa dura para o protocolo; a alternativa ambiental é oferecida no lugar.",
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A8.4",
    fonte: "A",
    secao: "§8.4 · Dietas restritivas",
    titulo: "Não apoiar dieta de exclusão como tratamento",
    papel: "limite",
    temas: ["nutricional"],
    gatilhos: [/\b(sem gl[úu]ten|sem lactose|dieta|case[íi]na|exclus[ãa]o|cura|tratamento alternativ\w*)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Dietas de exclusão (glúten, lactose) não são tratamento nem cura para o autismo e não se sustentam sem indicação e acompanhamento de nutrólogo ou pediatra.",
    investigar: [],
    prerequisitos: [],
    direcao: null,
    cautela: "Recusa dura.",
    procedencia: null,
    jaNoCore: false,
  },

  // ─────────────────────────── §10 · O que os 20 princípios acrescentam
  {
    id: "A10.11",
    fonte: "A",
    secao: "§10 · Princípio 11",
    titulo: "Semântica sem pragmática não é comunicação",
    papel: "principio",
    temas: ["comunicacao", "aprendizado", "escola"],
    gatilhos: [
      /\b(sabe (todas? )?(as |os )?(cores|n[úu]meros|letras|alfabeto)|conta at[ée]|decora|sabe tudo|repete tudo|fala (v[áa]rias|muitas) palavras)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Saber cores, números e falar muitas palavras é semântica. Usar linguagem para pedir, comentar, recusar e sustentar troca é pragmática. Um repertório grande convive com comunicação funcional ausente — e é a segunda que muda a vida.",
    investigar: ["comunicacao.conversa", "comunicacao.iniciativa", "comunicacao.forma"],
    prerequisitos: [],
    direcao: "Medir o uso social da linguagem, não o tamanho do vocabulário.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A10.18",
    fonte: "A",
    secao: "§10 · Princípios 18 e 19",
    titulo: "Não falar nem decidir pela criança — e modelar o alvo exato",
    papel: "principio",
    temas: ["comunicacao"],
    gatilhos: [
      /\b(j[áa] sei o que ele quer|antes (dele|dela) pedir|eu adivinho|nem precisa pedir|falo por ele)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Antecipar o desejo remove o motivo de comunicar. Criar pequenas sabotagens amigáveis obriga a iniciativa; e o modelo oferecido deve ser o alvo exato — uma palavra —, não uma frase longa ou um sermão que a criança não consegue processar.",
    investigar: ["comunicacao.iniciativa", "comunicacao.forma"],
    prerequisitos: [],
    direcao: "Abrir espaço para o pedido e modelar uma palavra, não uma explicação.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
  {
    id: "A10.20",
    fonte: "A",
    secao: "§10 · Princípio 20",
    titulo: "A comunicação é o eixo transversal mais crítico",
    papel: "principio",
    temas: ["comunicacao", "socializacao", "emocional", "autonomia"],
    gatilhos: [],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Sem comunicação funcional não há socialização real, redução sustentada de crises nem autonomia de vida. Quando várias frentes competem pela prioridade, a comunicação costuma ser a que destrava as outras.",
    investigar: ["comunicacao.forma", "comunicacao.iniciativa"],
    prerequisitos: [],
    direcao: "Em empate de prioridade, a comunicação vem primeiro.",
    cautela: null,
    procedencia: null,
    jaNoCore: false,
  },
];
