import type { UnidadeDaPos } from "./tipos";

/**
 * DOCUMENTO B — "Compêndio de Neurodesenvolvimento: Guia Mestre de
 * Pós-Graduação em TEA". 26.909 bytes, md5 `e433ce04…`, versionado em 10/09.
 *
 * É o documento que traz O QUE A CIÊNCIA DIZ, com citação numerada em quase
 * toda frase e a Parte 3 de grounding. Dá a B duas coisas que A não tem:
 * **faixa etária** e **procedência rastreável**.
 *
 * ⚠️ PARTE DE B JÁ FOI PROMOVIDA A PISO. O Core v11 (05/09) foi escrito depois
 * de B chegar (28/08) e absorveu a diretriz transversal e a tríade da apraxia,
 * reescritas na voz da Ayla. Essas unidades carregam `jaNoCore: true`: seguem
 * valendo como raciocínio e como pré-requisito, e NÃO são injetadas no prompt —
 * senão a pós repetiria no contexto o que o Core já diz melhor.
 */
export const UNIDADES_B: readonly UnidadeDaPos[] = [
  // ─────────── Diretriz de segurança clínica transversal
  {
    id: "B0.1",
    fonte: "B",
    secao: "Diretriz transversal · Sono",
    titulo: "Ronco crônico, respiração bucal e apneia pedem otorrino antes de plano de sono",
    papel: "sinal_de_alerta",
    temas: ["sono", "foco", "emocional"],
    gatilhos: [/\b(ronca|ronco|respira pela boca|boca aberta|apneia|para de respirar|baba no travesseiro)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Ronco crônico, respiração bucal e apneia fragmentam o sono e produzem, de dia, exatamente o quadro que se confunde com desatenção e irritabilidade. Montar plano comportamental de sono sem excluir a causa orgânica é tratar a consequência.",
    investigar: ["sono.adormece", "sono.despertares", "sono.atrapalha"],
    prerequisitos: [],
    direcao: "Sinalizar avaliação otorrinolaringológica antes de qualquer estratégia de higiene do sono.",
    cautela: "Sinalizar não é diagnosticar.",
    procedencia: "B [44, 119]",
    jaNoCore: true,
  },
  {
    id: "B0.2",
    fonte: "B",
    secao: "Diretriz transversal · Alimentação",
    titulo: "Engasgo recorrente e recusa abrupta pedem investigação de disfagia e refluxo",
    papel: "sinal_de_alerta",
    temas: ["nutricional"],
    gatilhos: [/\b(engasg\w*|tosse (quando|ao) com\w*|vomit\w*|golfa|refluxo|parou de comer|recusa (a )?comida)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Engasgos recorrentes, tosse ao comer ou recusa alimentar de início abrupto apontam disfagia mecânica ou refluxo. Recusa que COMEÇOU de repente é clinicamente diferente de seletividade instalada há anos.",
    investigar: ["nutricional.dificuldades", "nutricional.texturas_rejeita"],
    prerequisitos: [],
    direcao: "Excluir a causa mecânica antes de tratar como seletividade sensorial.",
    cautela: "Sinalizar não é diagnosticar.",
    procedencia: "B [53, 119]",
    jaNoCore: true,
  },
  {
    id: "B0.3",
    fonte: "B",
    secao: "Diretriz transversal · Uso do banheiro",
    titulo: "Constipação crônica e encoprese líquida pedem tratamento clínico imediato",
    papel: "sinal_de_alerta",
    temas: ["autonomia", "nutricional"],
    gatilhos: [/\b(n[ãa]o faz c[oô]c[oô]|prende|constipa\w*|intestino preso|dias sem|escapa|suja a cal[çc]a|encoprese|fezes duras)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Dias sem evacuar e escape líquido involuntário exigem tratamento clínico imediato para evitar megacólon funcional. E fezes duras doem: a criança trava preventivamente, o que é lido como recusa de desfralde quando é defesa contra dor.",
    investigar: ["autonomia.precisa_ajuda"],
    prerequisitos: [],
    direcao: "Tratar a constipação antes de qualquer plano de desfralde.",
    cautela: "Sinalizar não é diagnosticar.",
    procedencia: "B [41, 54, 119]",
    jaNoCore: true,
  },
  {
    id: "B0.4",
    fonte: "B",
    secao: "Diretriz transversal · Desregulação de início súbito",
    titulo: "Crise aguda inexplicável pede procurar DOR SILENCIOSA antes de comportamento",
    papel: "sinal_de_alerta",
    temas: ["emocional", "sono", "nutricional"],
    gatilhos: [
      /\b(do nada|de repente|come[çc]ou (do nada|de uma hora)|nunca foi assim|mudou (de uma hora|do nada)|piorou de repente|essa semana come[çc]ou|antes n[ãa]o era assim)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Crise aguda sem explicação, em criança que antes não era assim, exige investigar dor silenciosa — otite, dente, infecção urinária. A criança que não localiza nem nomeia a dor a expressa como desregulação, e o quadro é lido como piora comportamental.",
    investigar: ["emocional.gatilhos", "emocional.sinais"],
    prerequisitos: [],
    direcao: "Perguntar pelo corpo e sinalizar avaliação médica antes de propor manejo de comportamento.",
    cautela: "Sinalizar não é diagnosticar.",
    procedencia: "B [122]",
    jaNoCore: true,
  },

  // ─────────── Tema 1 · Diagnóstico e classificação
  {
    id: "B1.2",
    fonte: "B",
    secao: "Tema 1 · Transição diagnóstica",
    titulo: "Nomes antigos que as famílias ainda usam mapeiam para TEA",
    papel: "mecanismo",
    temas: ["essencial"],
    gatilhos: [/\b(asperger|kanner|TGD|desintegrativ\w*|Heller|autismo leve|autismo cl[áa]ssico)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "O DSM-5 unificou Asperger, autismo de Kanner, TGD-SOE e transtorno desintegrativo sob a nomenclatura única de TEA. Uma mãe que diz 'Asperger' está descrevendo um diagnóstico real, muitas vezes antigo — não um erro a corrigir.",
    investigar: ["saude_geral.acompanhamentos"],
    prerequisitos: [],
    direcao: "Aceitar o termo que a família usa e entender o que ele descreve, sem corrigir o vocabulário dela.",
    cautela: null,
    procedencia: "B [4, 122, 131]",
    jaNoCore: false,
  },
  {
    id: "B1.3",
    fonte: "B",
    secao: "Tema 1 · Os dois pilares (díade clínica)",
    titulo: "Critério A (comunicação social) e Critério B (padrões restritos e sensorial)",
    papel: "mecanismo",
    temas: ["essencial", "comunicacao", "socializacao", "sensorial"],
    gatilhos: [/\b(crit[ée]rio|DSM|di[áa]de|estereotip\w*|repetitiv\w*|ritual|rigidez)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "São dois domínios, avaliados separadamente: déficits persistentes em comunicação e interação social; e padrões restritos, repetitivos e estereotipados — onde entram rituais, rigidez a mudança, maneirismos e hiper ou hiporreatividade sensorial. O sensorial faz parte do critério, não é acessório.",
    investigar: ["socializacao.interage", "sensorial.perfil"],
    prerequisitos: [],
    direcao: "Ler queixa sensorial e queixa social como as duas metades do mesmo quadro.",
    cautela: null,
    procedencia: "B [6, 161]",
    jaNoCore: false,
  },
  {
    id: "B1.4",
    fonte: "B",
    secao: "Tema 1 · Níveis de suporte",
    titulo: "Nível 1, 2 e 3 descrevem QUANTO apoio, não quanto vale a criança",
    papel: "mecanismo",
    temas: ["essencial"],
    gatilhos: [/\bn[íi]vel [123]\b|\bsuporte (leve|substancial|muito substancial)\b|\bgrau\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Nível 1: verbal, com dificuldade pragmática e rigidez que atrapalha em um ou mais contextos. Nível 2: déficits marcantes mesmo com apoio, inflexibilidade óbvia. Nível 3: comunicação social gravemente prejudicada, pânico diante de mudanças. O nível é avaliado por domínio, não como um rótulo único.",
    investigar: ["saude_geral.acompanhamentos"],
    prerequisitos: [],
    direcao: "Usar o nível para calibrar a expectativa da orientação, nunca para reduzir a criança a ele.",
    cautela: null,
    procedencia: "B [54, 117, 118, 168]",
    jaNoCore: false,
  },
  {
    id: "B1.5",
    fonte: "A+B",
    secao: "Tema 1 · CID-11 · A §2",
    titulo: "CID-11 (6A02) separa por deficiência intelectual e por linguagem funcional",
    papel: "mecanismo",
    temas: ["essencial", "comunicacao", "aprendizado"],
    gatilhos: [/\bCID\b|\b6A02\b|\bdefici[êe]ncia intelectual\b|\blinguagem funcional\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "A CID-11 subdivide o TEA por duas variáveis de altíssimo impacto prático: presença ou ausência de deficiência intelectual associada, e presença ou ausência de linguagem funcional — a capacidade de usar comunicação para resolver demandas do dia.",
    investigar: ["saude_geral.acompanhamentos", "comunicacao.forma"],
    prerequisitos: [],
    direcao: "Separar 'tem linguagem' de 'usa linguagem para resolver a vida' — é a segunda que orienta.",
    cautela: null,
    procedencia: "B [6, 161]",
    jaNoCore: false,
  },

  // ─────────── Tema 2 · Comunicação e linguagem pragmática
  {
    id: "B2.1",
    fonte: "B",
    secao: "Tema 2 · PFC · Iniciativa comunicativa",
    titulo: "Atos comunicativos por minuto — a métrica funcional que o vocabulário esconde",
    papel: "marco_etario",
    temas: ["comunicacao"],
    gatilhos: [/\b(n[ãa]o pede|pede pouco|s[óo] fala quando|n[ãa]o inicia|quase n[ãa]o fala|fala sozinh\w*)\b/i],
    faixaMesesMin: 18,
    faixaMesesMax: 72,
    mecanismo:
      "O que se mede na avaliação funcional é quantos atos comunicativos a criança INICIA espontaneamente por minuto em interação face a face. Aos 30 meses, o esperado típico gira em torno de 6 por minuto. Uma criança com muitas palavras e pouquíssima iniciativa tem um problema que a contagem de vocabulário não mostra.",
    investigar: ["comunicacao.iniciativa", "comunicacao.conversa"],
    prerequisitos: ["A3.D"],
    direcao: "Observar quantas vezes ela COMEÇA, não quantas responde.",
    cautela: "Referência de literatura, não régua para cobrar da família. Nunca vira contagem em casa.",
    procedencia: "B [32, 128, 192] · Fernandes",
    jaNoCore: false,
  },
  {
    id: "B2.2",
    fonte: "B",
    secao: "Tema 2 · PFC · Meios comunicativos",
    titulo: "Verbal, vocal e gestual são três meios — e gestual é comunicação, não ausência dela",
    papel: "mecanismo",
    temas: ["comunicacao"],
    gatilhos: [/\b(gesto|aponta|puxa|grunh\w*|balbuci\w*|som|fala enrolad\w*|n[ãa]o d[áa] pra entender|CAA|prancha|figuras)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "A avaliação separa VERBAL (emissão com pelo menos 75% dos fonemas da língua), VOCAL (som que não atinge esse limiar) e GESTUAL (movimento corporal, facial, uso do corpo do outro). Uma criança que comunica muito por gesto tem meio comunicativo instalado — o alvo é ampliar, não substituir.",
    investigar: ["comunicacao.forma", "comunicacao.caa"],
    prerequisitos: [],
    direcao: "Reconhecer o meio que já funciona antes de puxar para o meio seguinte.",
    cautela: null,
    procedencia: "B [109, 192]",
    jaNoCore: false,
  },
  {
    id: "B2.3",
    fonte: "B",
    secao: "Tema 2 · PFC · Funções comunicativas",
    titulo: "Funções interativas × autocentradas — o que ela comunica, não só quanto",
    papel: "mecanismo",
    temas: ["comunicacao", "socializacao"],
    gatilhos: [/\b(s[óo] pede|s[óo] fala de|n[ãa]o comenta|n[ãa]o pergunta|n[ãa]o conta|monologa|fala sem parar)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Funções interativas (comentar, pedir informação, jogo compartilhado) e autocentradas (reativo, exploratório, não-focalizado) medem o QUÊ da comunicação. Uma criança que só pede tem função instalada, mas estreita — e o alvo clínico é diversificar, não aumentar volume.",
    investigar: ["comunicacao.conversa", "comunicacao.iniciativa"],
    prerequisitos: ["B2.2"],
    direcao: "Ampliar o repertório de funções — comentar e perguntar, não só pedir.",
    cautela: null,
    procedencia: "B [33, 109]",
    jaNoCore: false,
  },
  {
    id: "B2.4",
    fonte: "B",
    secao: "Tema 2 · Evolução das ecolalias",
    titulo: "Ecolalia tem função comunicativa e reguladora — é transição, não defeito",
    papel: "mecanismo",
    temas: ["comunicacao"],
    gatilhos: [/\b(repete (tudo|o que|frases|falas)|ecolalia|fala de desenho|repete propaganda|fala decorada|papagai\w*)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Repetir enunciados, músicas e falas de desenho — imediata ou tardiamente — é fenômeno comum na aquisição de linguagem no TEA. Hoje se reconhece função comunicativa ou reguladora nisso: é ponte para a fala espontânea, e some conforme vocabulário e pragmática crescem.",
    investigar: ["comunicacao.forma", "comunicacao.conversa"],
    prerequisitos: [],
    direcao: "Ler o que a ecolalia está tentando fazer e responder a isso, em vez de tentar extingui-la.",
    cautela: null,
    procedencia: "B [44]",
    jaNoCore: false,
  },

  // ─────────── Tema 3 · Apraxia de fala
  {
    id: "B3.1",
    fonte: "A+B",
    secao: "Tema 3 · Tríade AFI/CAS · A §4",
    titulo: "Inconsistência, distorção de vogais e prosódia — a tríade que separa apraxia de desvio fonológico",
    papel: "mecanismo",
    temas: ["comunicacao"],
    gatilhos: [
      /\b(fala diferente cada vez|cada hora de um jeito|n[ãa]o consigo entender|trocado|enrolad\w*|rob[óo]tic\w*|cantad\w*|apraxia)\b/i,
    ],
    faixaMesesMin: 24,
    faixaMesesMax: null,
    mecanismo:
      "Apraxia de fala é transtorno MOTOR de planejamento, sem fraqueza muscular: o cérebro sabe o que dizer e falha em sequenciar a boca. Os três sinais diferenciais são inconsistência (a mesma palavra sai diferente a cada tentativa), distorção de vogais e quebra de ritmo e acentuação.",
    investigar: ["comunicacao.forma"],
    prerequisitos: [],
    direcao: "Sinalizar avaliação fonoaudiológica específica quando a inconsistência é o traço marcante.",
    cautela: "A Ayla descreve os sinais; quem discrimina apraxia de desvio fonológico é o fonoaudiólogo.",
    procedencia: "B [34, 107] · Lopes-Herrera",
    jaNoCore: true,
  },

  // ─────────── Tema 4 · Processamento sensorial (Dunn)
  {
    id: "B4.1",
    fonte: "B",
    secao: "Tema 4 · Prevalência da DPS",
    titulo: "Alteração de processamento sensorial está em 30% a 100% dos casos",
    papel: "mecanismo",
    temas: ["sensorial"],
    gatilhos: [],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "A disfunção de processamento sensorial — inabilidade neurológica de receber, organizar, modular e responder às sensações do corpo e do ambiente — é encontrada na maioria dos casos de TEA. É regra, não exceção: vale considerá-la mesmo quando a queixa não é sensorial.",
    investigar: ["sensorial.perfil"],
    prerequisitos: [],
    direcao: "Considerar o sensorial como hipótese de fundo em queixas de comportamento, sono e alimentação.",
    cautela: null,
    procedencia: "B [143, 195, 206]",
    jaNoCore: false,
  },
  {
    id: "B4.2",
    fonte: "A+B",
    secao: "Tema 4 · Dunn · Hipersensibilidade",
    titulo: "Limiar BAIXO — o volume do mundo chega no máximo",
    papel: "mecanismo",
    temas: ["sensorial", "emocional", "nutricional", "foco"],
    gatilhos: [
      /\b(tapa (os )?ouvid\w*|barulho|som alto|etiqueta|costura|n[ãa]o usa (meia|roupa)|cortar (o )?(cabelo|unha)|luz|cheiro|textura|n[ãa]o gosta de ser tocad\w*)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Limiar neurológico baixo: o cérebro reage rápido e intensamente a estímulo pequeno. Tapar ouvidos para eletrodoméstico, pânico de etiqueta, aversão a corte de unha e cabelo, recusa de textura. Sob esse volume, o sistema entra em sobrevivência — e fuga ou agressividade são a saída.",
    investigar: ["sensorial.perfil", "sensorial.sons", "sensorial.toques", "sensorial.luz"],
    prerequisitos: [],
    direcao: "Baixar o volume do ambiente antes de pedir tolerância.",
    cautela: null,
    procedencia: "B [15, 54, 149] · Dunn",
    jaNoCore: false,
  },
  {
    id: "B4.3",
    fonte: "A+B",
    secao: "Tema 4 · Dunn · Baixo registro",
    titulo: "Limiar ALTO passivo — ela não sente o que deveria doer",
    papel: "mecanismo",
    temas: ["sensorial", "emocional"],
    gatilhos: [
      /\b(n[ãa]o sente dor|n[ãa]o chora quando|nem percebe|n[ãa]o reage|n[ãa]o responde quando chamo|n[ãa]o liga|se machuca e n[ãa]o)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Limiar alto com padrão passivo: a criança demora a perceber estímulos importantes — indiferença à dor de ferimento real, não notar sujeira na pele, não reagir ao chamado. Isso muda a leitura de 'me ignora' e, principalmente, esconde dor: ela pode estar com otite e não avisar.",
    investigar: ["sensorial.perfil", "sensorial.toques"],
    prerequisitos: [],
    direcao: "Não usar a reação da criança como termômetro de dor ou de escuta.",
    cautela: null,
    procedencia: "B [15, 54] · Dunn",
    jaNoCore: false,
  },
  {
    id: "B4.4",
    fonte: "A+B",
    secao: "Tema 4 · Dunn · Busca sensorial",
    titulo: "Limiar ALTO ativo — ela precisa de input intenso para se organizar",
    papel: "mecanismo",
    temas: ["sensorial", "foco", "emocional", "nutricional"],
    gatilhos: [
      /\b(se joga|bate (a cabe[çc]a|nas coisas)|se esbarra|gira|balan[çc]a|morde (tudo|tecido|roupa)|p[õo]e (tudo )?na boca|n[ãa]o para quiet\w*|agitad\w*|corre demais|aperta)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Limiar alto com padrão ativo de busca: bater-se contra paredes, balançar-se com vigor, morder tecidos, pôr objetos na boca, buscar giro rápido e comida muito crocante. Não é agitação sem propósito — é o corpo procurando a intensidade que falta para se registrar.",
    investigar: ["sensorial.perfil", "sensorial.movimento", "sensorial.toques"],
    prerequisitos: [],
    direcao: "Oferecer o input intenso de forma organizada e previsível, antes que o corpo o procure sozinho.",
    cautela: null,
    procedencia: "B [15, 54, 148] · Dunn",
    jaNoCore: false,
  },

  // ─────────── Tema 5 · Autocuidado e alimentação
  {
    id: "B5.1",
    fonte: "B",
    secao: "Tema 5 · Comportamento adaptativo",
    titulo: "O nível de suporte é definido pelas barreiras do ambiente real, não pelo QI",
    papel: "mecanismo",
    temas: ["autonomia", "essencial", "escola"],
    gatilhos: [/\b(autonomia|sozinh\w*|depende de mim|faz tudo por ele|n[ãa]o consegue sozinh\w*|independ[êe]nci\w*)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Comportamento adaptativo é a independência funcional conceitual, prática e social exigida na vida diária. O grau de suporte está atrelado às barreiras de funcionamento no ambiente real de inserção — a mesma criança precisa de mais ou menos apoio conforme o ambiente.",
    investigar: ["autonomia.padrao", "autonomia.precisa_ajuda"],
    prerequisitos: [],
    direcao: "Perguntar qual ambiente, não só qual criança.",
    cautela: null,
    procedencia: "B [117, 132, 311, 388]",
    jaNoCore: false,
  },
  {
    id: "B5.2",
    fonte: "B",
    secao: "Tema 5 · Alimentação multimodal",
    titulo: "Seletividade severa costuma ser defensividade tátil-oral, não manha",
    papel: "mecanismo",
    temas: ["nutricional", "sensorial"],
    gatilhos: [
      /\b(s[óo] come|n[ãa]o come|seletiv\w*|comida|papinha|textura|n[ãa]o aceita (comida|nada)|enjoad\w*|s[óo] aceita)\b/i,
    ],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "Comer envolve visão de cor, som de crocância, tato oral de consistência e cheiro ao mesmo tempo. No TEA, a seletividade severa decorre com frequência de defensividade tátil-oral e hipersensibilidade olfativa e visual — a criança não está escolhendo, está se defendendo.",
    investigar: ["nutricional.texturas_rejeita", "nutricional.dificuldades", "sensorial.perfil"],
    prerequisitos: ["B4.2", "B0.2"],
    direcao: "Aproximar por tolerância gradual fora da hora da refeição — tocar e cheirar antes de provar.",
    cautela: "Excluir causa mecânica (B0.2) antes de tratar como sensorial.",
    procedencia: "B [195, 199, 201, 207]",
    jaNoCore: false,
  },
  {
    id: "B5.3",
    fonte: "B",
    secao: "Tema 5 · Controle esfincteriano",
    titulo: "Desfralde atrasa em média 1,6 ano para urina e mais de 2 para o intestino",
    papel: "marco_etario",
    temas: ["autonomia"],
    gatilhos: [/\b(desfralda\w*|fralda|xixi|penico|vaso|banheiro|n[ãa]o avisa|faz na cal[çc]a)\b/i],
    faixaMesesMin: 24,
    faixaMesesMax: 120,
    mecanismo:
      "No TEA o controle urinário costuma se estabelecer com cerca de 1,6 ano de atraso, e o intestinal com mais de 2. Três barreiras concretas: estabilidade postural (pé firme apoiado, redutor de assento), previsibilidade visual, e constipação não tratada.",
    investigar: ["autonomia.precisa_ajuda"],
    prerequisitos: ["B0.3"],
    direcao: "Estabilizar postura e excluir constipação antes de cobrar o controle.",
    cautela: "O atraso é referência de literatura — serve para acalmar a família, nunca para adiar apoio.",
    procedencia: "B [15, 17, 25, 137]",
    jaNoCore: false,
  },

  // ─────────── Tema 6 · Escola, pares e mídia
  {
    id: "B6.1",
    fonte: "B",
    secao: "Tema 6 · Status sociométrico",
    titulo: "Isolado negligenciado × isolado controverso — dois isolamentos diferentes",
    papel: "mecanismo",
    temas: ["socializacao", "escola"],
    gatilhos: [
      /\b(sozinh\w* (na|no) (escola|recreio)|n[ãa]o tem amig\w*|ningu[ée]m brinca|exclu[íi]d\w*|bullying|briga na escola|se mete em confus)\b/i,
    ],
    faixaMesesMin: 48,
    faixaMesesMax: null,
    mecanismo:
      "Pesquisa de pátio descreve dois lugares distintos: o isolado NEGLIGENCIADO, que fica só e sem atrito, e o isolado CONTROVERSO, que se envolve em conflito frequente por não ler as regras invisíveis. São causas diferentes e pedem intervenções diferentes.",
    investigar: ["socializacao.com_quem", "socializacao.interage", "escola.queixas"],
    prerequisitos: [],
    direcao: "Distinguir qual dos dois isolamentos é o caso antes de propor qualquer ação social.",
    cautela: null,
    procedencia: "B [80]",
    jaNoCore: false,
  },
  {
    id: "B6.2",
    fonte: "B",
    secao: "Tema 6 · Mediação ativa de pares",
    titulo: "Socialização não acontece por proximidade física",
    papel: "mecanismo",
    temas: ["socializacao", "escola"],
    gatilhos: [/\b(escola|professora?|sala|inclus[ãa]o|recreio|colegas|turma|adapta\w*)\b/i],
    faixaMesesMin: 36,
    faixaMesesMax: null,
    mecanismo:
      "Estar na mesma sala não produz interação. O que produz é estrutura ativa: grupos pequenos de aprendizagem cooperativa, brincadeira com regra explícita ancorada no interesse da criança, e colegas típicos preparados como apoio. E exige o professor sair da cobrança para a mediação.",
    investigar: ["escola.funciona", "escola.queixas", "socializacao.com_quem"],
    prerequisitos: ["B6.1"],
    direcao: "Pedir estrutura mediada à escola, não mais tempo de convivência.",
    cautela: null,
    procedencia: "B [15, 66, 80, 114]",
    jaNoCore: false,
  },
  {
    id: "B6.3",
    fonte: "B",
    secao: "Tema 6 · Mídia e Teoria da Mente",
    titulo: "Narrativa pausável é ensaio cognitivo de Teoria da Mente",
    papel: "mecanismo",
    temas: ["socializacao", "aprendizado", "tela_midia"],
    gatilhos: [/\b(desenho|v[íi]deo|s[ée]rie|filme|jogo|hist[óo]ria|livro|tela|youtube)\b/i],
    faixaMesesMin: 36,
    faixaMesesMax: null,
    mecanismo:
      "Observar interação representada por personagens, em condição previsível e pausável, permite analisar falsas crenças e prever estados mentais sem a pressão de tempo real de uma conversa. A tela que a família vê como problema pode ser o único laboratório social disponível.",
    investigar: ["tela_midia.padrao", "socializacao.interage"],
    prerequisitos: ["A7.4"],
    direcao: "Usar a narrativa que ela já ama como ensaio, em vez de disputar o tempo de tela.",
    cautela: null,
    procedencia: "B [98, 127, 129]",
    jaNoCore: false,
  },

  // ─────────── Tema 7 · Vida adulta
  {
    id: "B7.1",
    fonte: "B",
    secao: "Tema 7 · Fenótipo ampliado (FAA/BAP)",
    titulo: "Traços subclínicos em pais e parentes são descritos e esperados",
    papel: "mecanismo",
    temas: ["essencial", "emocional"],
    gatilhos: [/\b(eu tamb[ée]m sou assim|puxou a mim|meu marido [ée]|eu era assim|acho que eu tenho|na fam[íi]lia tem)\b/i],
    faixaMesesMin: null,
    faixaMesesMax: null,
    mecanismo:
      "O fenótipo ampliado descreve traços sutis de rigidez, preferência por rotina fixa e dificuldade pragmática leve em pais e parentes biológicos, sem atingir limiar clínico. Quando a mãe se reconhece no filho, ela está descrevendo um fenômeno documentado.",
    investigar: [],
    prerequisitos: [],
    direcao: "Acolher o reconhecimento sem transformá-lo em avaliação da mãe.",
    cautela: "Jamais sugerir que a mãe se avalie ou se diagnostique. O assunto é da criança.",
    procedencia: "B [23, 60, 68]",
    jaNoCore: false,
  },
  {
    id: "B7.2",
    fonte: "B",
    secao: "Tema 7 · Masking e burnout",
    titulo: "Camuflagem sistemática esgota — e o colapso chega depois, em casa",
    papel: "mecanismo",
    temas: ["emocional", "escola", "socializacao"],
    gatilhos: [
      /\b(na escola (ele )?([ée]|se comporta|[ée] um anjo)|professora? (diz|fala) que|s[óo] (em casa|comigo)|segura (tudo )?e explode|chega em casa e|na frente dos outros|se comporta fora|[ée] um anjo)\b/i,
    ],
    faixaMesesMin: 60,
    faixaMesesMax: null,
    mecanismo:
      "A camuflagem sistemática de sintomas para caber no ambiente social tem custo mental alto e cumulativo. 'Na escola é ótimo, em casa explode' costuma descrever isso: a casa é onde o esforço de sustentação finalmente cede, não onde o problema está.",
    investigar: ["emocional.gatilhos", "escola.funciona"],
    prerequisitos: [],
    direcao: "Ler a explosão em casa como conta do dia, e reduzir a demanda do dia.",
    cautela: null,
    procedencia: "B [22, 23, 95]",
    jaNoCore: false,
  },
  {
    id: "B7.3",
    fonte: "B",
    secao: "Tema 7 · Barreiras adaptativas e laborais",
    titulo: "Adultos autistas têm as maiores taxas de desemprego entre todas as deficiências",
    papel: "mecanismo",
    temas: ["autonomia", "essencial"],
    gatilhos: [/\b(futuro|quando crescer|trabalh\w*|emprego|faculdade|vida adulta|vai conseguir)\b/i],
    faixaMesesMin: 144,
    faixaMesesMax: null,
    mecanismo:
      "Mesmo com inteligência na média ou acima e alta escolaridade, adultos autistas enfrentam as maiores taxas de desemprego e subemprego. As barreiras concretas são entrevista baseada em carisma, regras não escritas da empresa e esgotamento por camuflagem — não capacidade técnica.",
    investigar: ["autonomia.padrao"],
    prerequisitos: ["B7.2"],
    direcao: "Ancorar a preocupação com o futuro em preparação e mediação, que são as alavancas que existem.",
    cautela: "Nunca usar o dado como prognóstico da criança específica.",
    procedencia: "B [16, 21, 22]",
    jaNoCore: false,
  },
  {
    id: "B7.4",
    fonte: "B",
    secao: "Tema 7 · Suportes organizacionais",
    titulo: "Quatro pilares: preparação, intermediação, adaptação ambiental e saúde mental",
    papel: "mecanismo",
    temas: ["autonomia"],
    gatilhos: [/\b(trabalh\w*|emprego|est[áa]gio|contrata\w*|job coach|inclus[ãa]o (no|de) trabalho)\b/i],
    faixaMesesMin: 168,
    faixaMesesMax: null,
    mecanismo:
      "A inclusão laboral que se sustenta apoia-se em quatro pilares: preparação vocacional antes do ingresso; intermediação ativa (job coach traduzindo demandas nos dois sentidos); adaptação do ambiente (abafador, luz, posto com menos circulação); e monitoramento de saúde mental.",
    investigar: ["autonomia.padrao"],
    prerequisitos: ["B7.3"],
    direcao: "Tratar inclusão laboral como estrutura a montar, não como qualidade a ter.",
    cautela: null,
    procedencia: "B [12, 15, 21, 22, 23, 94]",
    jaNoCore: false,
  },

  // ─────────── Parte 2 · Cronograma por faixas etárias
  {
    id: "BP2.1",
    fonte: "B",
    secao: "Parte 2 · 0 a 3 anos",
    titulo: "Marcos de 6-9, 9-18 e 18-30 meses",
    papel: "marco_etario",
    temas: ["comunicacao", "socializacao", "motor", "aprendizado"],
    gatilhos: [],
    faixaMesesMin: 0,
    faixaMesesMax: 36,
    mecanismo:
      "6-9m: balbucio com sílabas repetidas, localização sonora, inibição ao 'não', imitação de jogos gestuais. 9-18m: resposta consistente ao próprio nome, atenção compartilhada emergindo, gesto de apontar para pedir e para mostrar. 18-30m: triangulação ocular ativa, primeiras palavras isoladas e combinadas, brincar de causa e efeito.",
    investigar: ["comunicacao.contato", "comunicacao.mostra", "comunicacao.forma"],
    prerequisitos: [],
    direcao: "Rastrear a integridade dos precursores não-verbais, que é o foco desta faixa.",
    cautela: "Marco é referência populacional, não cobrança. A Ayla usa para orientar o olhar, nunca para alarmar.",
    procedencia: "B [18, 123, 129, 179, 186]",
    jaNoCore: false,
  },
  {
    id: "BP2.2",
    fonte: "B",
    secao: "Parte 2 · 3 a 5 anos",
    titulo: "Fala funcional em orações, brincar paralelo e simbólico, desfralde",
    papel: "marco_etario",
    temas: ["comunicacao", "socializacao", "autonomia", "nutricional"],
    gatilhos: [],
    faixaMesesMin: 36,
    faixaMesesMax: 71,
    mecanismo:
      "Esperado: fala expressiva em orações completas para desejo, intenção e relato; transição do brincar solitário para o paralelo e início do faz-de-conta; independência básica em comer, colaborar no vestir e iniciar o controle esfincteriano. O foco desta faixa é consistência da fala, mastigação e deglutição, sono e desfralde.",
    investigar: ["comunicacao.conversa", "socializacao.interage", "autonomia.precisa_ajuda"],
    prerequisitos: ["BP2.1"],
    direcao: "Olhar inteligibilidade e brincar simbólico, que são os marcadores desta faixa.",
    cautela: "Marco é referência populacional, não cobrança.",
    procedencia: "B [15, 61, 80, 137]",
    jaNoCore: false,
  },
  {
    id: "BP2.3",
    fonte: "B",
    secao: "Parte 2 · 6 a 12 anos",
    titulo: "Funções executivas de alto nível, grafomotricidade e brincar cooperativo por regra",
    papel: "marco_etario",
    temas: ["escola", "foco", "motor", "socializacao", "aprendizado"],
    gatilhos: [],
    faixaMesesMin: 72,
    faixaMesesMax: 155,
    mecanismo:
      "Esperado: leitura e escrita formais; controle inibitório para esperar a vez, flexibilidade para tolerar mudança de plano, memória de trabalho para instrução em sequência; pinça do lápis, tesoura, amarrar sapato; brincar cooperativo com regra. O foco é pragmática conversacional, motricidade fina escrita, organização executiva e posição social na escola.",
    investigar: ["escola.queixas", "escola.funciona", "foco.sustenta", "motor.fino"],
    prerequisitos: ["BP2.2"],
    direcao: "Separar dificuldade executiva de dificuldade de conteúdo — elas pedem apoios diferentes.",
    cautela: "Marco é referência populacional, não cobrança.",
    procedencia: "B [66, 78, 80, 88, 90, 98]",
    jaNoCore: false,
  },
  {
    id: "BP2.4",
    fonte: "B",
    secao: "Parte 2 · 13 a 17 anos",
    titulo: "Pragmática abstrata, puberdade e autonomia comunitária",
    papel: "marco_etario",
    temas: ["socializacao", "autonomia", "emocional", "escola"],
    gatilhos: [],
    faixaMesesMin: 156,
    faixaMesesMax: 215,
    mecanismo:
      "Esperado: maturação da puberdade e emergência da sexualidade; compreensão de subtexto, sarcasmo, ironia e gíria do grupo; autonomia de transporte, dinheiro e organização do tempo. O foco é identidade, regulação de humor, ansiedade social de desempenho, vulnerabilidade a cyberbullying e a abuso por credulidade pragmática.",
    investigar: ["socializacao.interage", "autonomia.padrao", "emocional.gatilhos"],
    prerequisitos: ["BP2.3"],
    direcao: "Tratar credulidade pragmática como risco de segurança concreto nesta faixa.",
    cautela: "Marco é referência populacional, não cobrança.",
    procedencia: "B [15, 60, 134]",
    jaNoCore: false,
  },
  {
    id: "BP2.5",
    fonte: "B",
    secao: "Parte 2 · 18 anos ou mais",
    titulo: "Independência adaptativa, inserção produtiva e autoadvocacia",
    papel: "marco_etario",
    temas: ["autonomia", "essencial"],
    gatilhos: [],
    faixaMesesMin: 216,
    faixaMesesMax: null,
    mecanismo:
      "Esperado: independência adaptativa plena, inserção produtiva compatível com a formação, e autoadvocacia — conhecer os próprios direitos e saber pedir adaptação razoável. O foco é funcionamento adaptativo, esgotamento crônico por camuflagem, e diagnóstico tardio.",
    investigar: ["autonomia.padrao"],
    prerequisitos: ["BP2.4"],
    direcao: "Olhar autoadvocacia como habilidade a ensinar, não como traço a esperar.",
    cautela: "Marco é referência populacional, não cobrança.",
    procedencia: "B [14, 15, 21, 22, 23, 95, 100, 311]",
    jaNoCore: false,
  },
];
